### ISSUE TITLE
Initial Window State And Style

### ISSUE THREAD

**Issue by danielmeloalencar** [wnayes/bond-wm#14]
As I mentioned in another comment, it would be very useful to have the possibility to open an application at a specific initial position (x,y). And also to define the style and initial state of the window (awaysOnTop, Normal, Maximized, Minimized).
And a flag to hide the application from the taskbar.

This would make it possible to create widgets.

**Comment by wnayes** [comment]
Note that:

- The concept of "always on top" is not yet implemented in the window manager (for `ChildWindow` or really any window). That would be a separate enhancement to support `_NET_WM_STATE_ABOVE`.
- Initial property overrides for regular windows can be applied via `onWindowCreated` on an `IConfig`. However, `ChildWindow` are not able to be configured this way since they are controlled programmatically (via React props) and not managed by the window manager. There isn't an API to maximize/minimize a `ChildWindow` though their size and visibility can be controlled, which could almost be considered the same thing for a borderless window.
- `ChildWindow` instances are always hidden from the taskbar currently, as they are not managed by the window manager.

**Comment by wnayes** [comment]
"Always on top" is implemented now in https://github.com/wnayes/bond-wm/commit/77ba87d92b477b9a69fe03e160a1e8ae678ba446
