### ISSUE TITLE
Rounded corners in windows

### ISSUE THREAD

**Issue by danielmeloalencar** [wnayes/bond-wm#3]
First, congratulations on the project. You are a genius!
I would like to know if it is possible to leave the windows with rounded corners

**Comment by wnayes** [comment]
I've been trying this out and I haven't been able to get it to work yet. I think it should be possible to just style the `.winWrapper` with border-radius and that would be it, however there may be bugs in Electron that prevent transparency from working.

I am getting a black fill color in the corners instead of transparency when I try:

![image](https://user-images.githubusercontent.com/1417866/178879561-fdc95043-06d6-4532-8a39-5097235659df.png)

**Comment by danielmeloalencar** [comment]
Following this tutorial I managed to make the window background transparent, but using other window managers. With electron-wm it doesn't work:

https://ourcodeworld.com/articles/read/315/how-to-create-a-transparent-window-with-electron-framework

**Comment by MAP94** [comment]
I guess you need to run a compositor (try xcompmgr) alongside the window manager

**Comment by danielmeloalencar** [comment]
It almost worked, problem that when I drag the window it looks like this and the desktop and taskbar disappear
![image](https://user-images.githubusercontent.com/74947997/181279993-3b009c2d-9634-405f-ab2f-f8495add1368.png)

**Comment by wnayes** [comment]
I had luck with the [picom](https://wiki.archlinux.org/title/picom) compositor. xcompmgr as mentioned above seemed to cause a lot of tearing/artifacts, but picom so far from what I've seen has made things better and resolved transparency issues. The default settings for picom are kind of opinionated (introduces extra shadows/fading) but these things can be disabled in picom.conf.

![image](https://github.com/wnayes/electron-wm/assets/1417866/57d35cbd-c34b-4dea-ae3e-02f7e4053f9c)

**Comment by wnayes** [comment]
Closing this issue, since this seems to work well with picom.
