### ISSUE TITLE
div over programs

### ISSUE THREAD

**Issue by danielmeloalencar** [wnayes/bond-wm#8]
In packages/react-config/desktop.tsx, how can I make my component or div  stay on top of any open application?

**Comment by danielmeloalencar** [comment]
Yes, and the possibility of positioning this browser window as you wish in relation to the width and height of the screen. A use case would be to create a start menu or a top panel, for example.

**Comment by wnayes** [comment]
Here's an article that describes how this sort of thing might be possible:
https://pietrasiak.com/creating-multi-window-electron-apps-using-react-portals

The "`ChildWindow`" described in that article would probably be something that would live in the [react](https://github.com/wnayes/bond-wm/tree/main/packages/react) package in this repository, which is the place where all the general React-related functionality lives.

There are only separate packages for things like wallpaper because they are "pluggable" aspects of the window manager that don't have to be used. It also makes them potentially a little bit easier to copy out and fork from if someone wanted to create derivative packages.

**Comment by wnayes** [comment]
I would eventually get around to implementing it I think, but would also accept a PR for it.

**Comment by danielmeloalencar** [comment]
> I would eventually get around to implementing it I think, but would also accept a PR for it.

To do this, we need the ability to render components in a window without a title bar and transparent, in addition to being able to set the position, width and height of the window. This way we could create a start menu.

**Comment by danielmeloalencar** [comment]
> I would eventually get around to implementing it I think, but would also accept a PR for it.

I will try to do it

**Comment by danielmeloalencar** [comment]
First attempt [here ](https://github.com/wnayes/bond-wm/issues/11 )
